export default {
  MANAGE_USERS: 'manage_users',
  MANAGE_ROLES: 'manage_roles',
  MANAGE_EVENTS: 'manage_events',
  MANAGE_PARTICIPANTS: 'manage_participants',
  DELETE_PARTICIPANTS: 'delete_participants',
  DELETE_PARTICIPANT_ATTENDANCE: 'delete_participant_attendance',
  CREATE_PARTICIPANT: 'create_participant',
  UPDATE_PARTICIPANT: 'update_participant',
  VIEW_FACULTY_PARTICIPANTS: 'view_faculty_participants',
  VIEW_ALL_PARTICIPANTS: 'view_all_participants',
  VIEW_CAREER_PARTICIPANTS: 'view_career_participants',
  HARD_DELETE_PARTICIPANT: 'hard_delete_participant',
  CREATE_PERMISSIONS: 'create_permissions',
  GET_PERMISSIONS: 'get_permissions',
  GET_PERMISSION: 'get_permission',
  UPDATE_PERMISSION: 'update_permission',
  DELETE_PERMISSION: 'delete_permission',
  HARD_DELETE_PERMISSION: 'hard_delete_permission',
};
